name: Fetch updates to latest code from master repo
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull latest version
        run: |
          git clone https://github.com/diarmidmackenzie/split-sub-directory
          cp -R split-sub-directory/examples/example1/* .
          rm -r split-sub-directory

      - name: Push to Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated from latest code"
          git push

